### PR TITLE
feathers-vuex 1.0 support

### PR DESCRIPTION
**Pull request by FossPrime**
- feathers-vuex updated to pre.3
- rxjs and feathers-reactive removed, Vue reactivity retained #36
- npm start alias, like vuejs-templates webpack

### CODE REVIEW

**Comment by marshallswain** [comment]
I forgot to say "Thank you!" when I saw this, originally.  So, @rayfoss, Thank you!

I'm just about ready to ship `feathers-vuex@1.0.0`.  I have a couple of utilities that I'm building for simplifying use in Nuxt apps, then I'll merge and release everything.

**Comment by COLABORATI** [comment]
Hi, I am interested in this one, thank you very much for your efforts!
However, I tried your branch with `feathers-vuex 1.0.0-pre.2` locally but I get some errors:
```
[Vue warn]: Invalid prop: type check failed for prop "messages". Expected Array, got Object.

found in

---> <MessageList> at src/components/Chat/Messages.vue
       <ChatApp> at src/components/Chat/Chat.vue
         <App> at src/App.vue
           <Root>

[Vue warn]: Error in render function: "TypeError: Cannot read property 'avatar' of undefined"

found in

---> <SingleMessage> at src/components/Chat/Message.vue
       <MessageList> at src/components/Chat/Messages.vue
         <ChatApp> at src/components/Chat/Chat.vue
           <App> at src/App.vue
             <Root>
```
There are some more errors visible in the browser console. 
Messages are sent successfully, I can see them in the original [feathers-chat](https://github.com/feathersjs/feathers-chat) clients, but in this version of feathers-chat-vuex the chat window remains empty. The users are, however, visible! 

I did this (just simply followed the install instructions): 
```
git clone https://github.com/feathersjs/feathers-chat
cd feathers-chat
npm install
npm start
cd ..
git clone https://github.com/rayfoss/feathers-chat-vuex.git
cd feathers-chat-vuex
git checkout feathers-vuex-1.0
npm install
npm run dev
```
As messages are sent, this seems to be a minor issue...

**Comment by COLABORATI** [comment]
And yes, I checked with some fake user@example.com - seems like that email address does not get an avatar and this condition is not handled? Just guessing.

**Comment by COLABORATI** [comment]
No, it gets the standard avatar icon, so something else.

**Comment by FossPrime** [comment]
@COLABORATI it sounds like something is expecting things to be acceed via mystore.data.avatar when the new API expects mystore.avatar ... somewhere

**Comment by COLABORATI** [comment]
BTW I would really love to see how you are debugging this! I am looking at the Chromium console and have vue dev tools installed, but I am not able to find the hot spot... vue dev tools do not give me any hint at all that there is something going wrong... that would be great if you just described how to spot the problem!

**Comment by COLABORATI** [comment]
I can see in vue dev tools that all messages are actually there, so just some rendering going wrong.

**Comment by COLABORATI** [comment]
restarted node, actually the first error message is:
```
[Vue warn]: Invalid prop: type check failed for prop "messages". Expected Array, got Object.

found in

---> <MessageList> at src/components/Chat/Messages.vue
       <ChatApp> at src/components/Chat/Chat.vue
         <App> at src/App.vue
           <Root>
```

**Comment by FossPrime** [comment]
@COLABORATI what node version are you running?
```
$ npm -v
5.4.0
$ node -v
v8.1.4
```

**Comment by FossPrime** [comment]
@COLABORATI As I suspected... check if that works it was looking for data... had to reinstall to see the issue. Im debugging the same way you are.

**Pull request merged**
